---
- name: install & start nginx
  hosts: all
  become: true

  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: latest

  - name: start nginx
    service:
      name: nginx
      state: started
