pipeline {
    agent any
    stages {
        stage('Check Ansible Version') {
            steps {
                sh 'ansible --version'
            }
        }
       stage ('ansible invoke') {
           steps {
                
         
    }
}
